version: '3'

services:
  postgres:
    image: postgres:15.4
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.85.0
    ports:
      - 4317:4317
