version: '3'

services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.82.0
    ports:
      - "4317:4317"
  # foosvc:
  #   build:
  #     context: ./../
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:8080"
  #   restart: always 
  #   depends_on:
  #     - postgres
  #   environment:
  #     SERVER_ADDR: ':8000'
  #     SERVER_READ_TIMEOUT: '5s'
  #     SERVER_WRITE_TIMEOUT: '10s'
  #     WORKER_QUEUE_SIZE: 5
  #     POSTGRES_URL: "postgres://postgres:password@127.0.0.1:5432/postgres?sslmode=disable"
  #     POSTGRES_MAX_CONNS: 4
  #     POSTGRES_MAX_IDLE_TIME: '1h'
  #     POSTGRES_MAX_LIFE_TIME: '30m'
  #     GOOGLE_APPLICATION_CREDENTIALS: "./service-account.json"
  #     TELEMETRY_ENABLED: "true"
  #     TELEMETRY_COLLECTOR_URL: ""
  #     TELEMETRY_SERVICE_NAME: "foo-service"
  #     TELEMETRY_ENV: "development"

